apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  selector:
    app.kubernetes.io/instance: grade-submission-api
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 31001