apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-api-secret
  namespace: grade-submission  # optional if default
type: Opaque
data:
  # Base64-encoded key-value pairs
  MONGODB_USER: YWRtaW4=      # echo -n "admin" | base64
  MONGODB_PASSWORD: cGFzc3dvcmQxMjM0  # echo -n "password1234" | base64
