apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: grade-submission
spec:
  selector:
    app.kubernetes.io/instance: mongodb
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017
